routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('on_construction');
// });

// Route::get('/rough', function () {
//     return view('rough');
// });

Route::get('/reports/index', [App\Http\Controllers\MainController::class, 'view_reports'])->middleware('auth');
Route::get('/reports/datatable', [App\Http\Controllers\MainController::class, 'datatable_reports'])->middleware('auth');

Route::get('/', [App\Http\Controllers\MainController::class, 'homepage'])->name('home');

//payment routes

Route::get('/payment/done/{id}', [App\Http\Controllers\MainController::class, 'payment_done']);
Route::get('/payment/cancel/{id}', [App\Http\Controllers\MainController::class, 'cancel_payment']);

Route::post('/cancel_trip_description', [App\Http\Controllers\MainController::class, 'cancel_trip_description'])->name('cancel_trip_description');

Route::get('/map', [App\Http\Controllers\MainController::class, 'map']);
Route::post('/check_user', [App\Http\Controllers\MainController::class, 'check_user']);
Route::post('/save_booking', [App\Http\Controllers\MainController::class, 'booking_details_update']);
Route::post('/store_book_details', [App\Http\Controllers\MainController::class, 'store_book_details']);
Route::post('/cancel_booking', [App\Http\Controllers\MainController::class, 'cancel_booking'])->name('cancel_booking');
Route::post('/quatation_request', [App\Http\Controllers\MainController::class, 'quatation_request'])->name('quatation_request');

Route::post('/exchange_rate_store',  [App\Http\Controllers\HomeController::class, 'RateStore'])->name('exchange.store');
Route::get('/contacts', [App\Http\Controllers\MainController::class, 'contacts']);
Route::get('/gallery', [App\Http\Controllers\MainController::class, 'gallery']);
Route::post('/check_available_post', [App\Http\Controllers\MainController::class, 'check_available_post_func']);
Route::delete('/delete_house', [App\Http\Controllers\MainController::class, 'delete_house']);
Route::delete('/delete_image', [App\Http\Controllers\MainController::class, 'delete_image']);

Route::get('/check_available', [App\Http\Controllers\MainController::class, 'check_available']);
Route::get('/book/{id}', [App\Http\Controllers\MainController::class, 'book']);
Route::get('/activity/{id}', [App\Http\Controllers\MainController::class, 'view_activity']);

Route::get('/home/booking/checkout/{id}', [App\Http\Controllers\MainController::class, 'checking_out_guest']);
Route::post('booking_details_update', [App\Http\Controllers\MainController::class, 'booking_details_update']);
Route::get('booking_details/{id}', [App\Http\Controllers\MainController::class, 'booking_details']);
Route::post('login_checker', [App\Http\Controllers\MainController::class, 'login_checker']);

Auth::routes();

Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home/check_in', [App\Http\Controllers\MainController::class, 'check_in'])->middleware('auth');
Route::get('/home/check_out', [App\Http\Controllers\MainController::class, 'check_out'])->middleware('auth');
Route::get('/home/booked', [App\Http\Controllers\MainController::class,  'booked'])->middleware('auth');
Route::get('/home/users', [App\Http\Controllers\MainController::class, 'users'])->middleware('auth');
Route::get('/home/content_manager', [App\Http\Controllers\MainController::class, 'content_manager'])->middleware('auth');
Route::resource('/home/content_manager/feature', App\Http\Controllers\FeatureController::class)->middleware('auth');
Route::resource('/home/content_manager/gallery_category', App\Http\Controllers\GalleryCategoryController::class)->middleware('auth');
Route::resource('/home/content_manager/image', App\Http\Controllers\ImageController::class)->middleware('auth');
Route::resource('/home/content_manager/facility', App\Http\Controllers\FacilityController::class)->middleware('auth');
Route::resource('/home/content_manager/activity', App\Http\Controllers\ActivityController::class)->middleware('auth');
Route::resource('/home/content_manager/category', App\Http\Controllers\CategoryController::class)->middleware('auth');
Route::resource('/home/content_manager/house', App\Http\Controllers\HouseController::class)->middleware('auth');
Route::resource('/home/booking', App\Http\Controllers\BookingController::class);
Route::post('/home/image_upload', [App\Http\Controllers\JsonResponseImageController::class, 'upload'])->name('json_upload_image');
Route::resource('/feedback', App\Http\Controllers\FeedbackController::class);
Route::resource('/booking_details', App\Http\Controllers\BookingDetailController::class);
Route::resource('/home/user', App\Http\Controllers\UserController::class);
Route::post('/save_exchange_rate', [App\Http\Controllers\MainController::class, 'save_exchange_rate']);

Route::get('/online_migrate', function() {
    $exitCode = Artisan::call('migrate');    
    // $exitCode = Artisan::call('migrate:fresh --seed');    
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('optimize:clear');
    return 'changes commited';
});

resources/views/Inc/Modal/add_activity.blade.php
<div class="modal fade" id="add_activity" tabindex="-1" style="display: none;" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Add Activity</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<form method="POST" action="{{  route('activity.store') }}" enctype='multipart/form-data'>
				@csrf
				<div class="modal-body">
					<div class="form-floating" >
						<label for="title" style="margin-top: -11px;">Title:</label>
						<input type="text" required placeholder="title" class="form-control" id="title" placeholder="Eg Clean Beach" name="title">
						{{-- {{ Form::file('file',null,['autofocus'=>'','required'=>'','class'=>'form-control','placeholder'=>'eg fastest cars in the world',  'maxlength'=>'1000', 'minlength'=>'1']) }} --}}
					</div>


					<div class="form-floating" style="padding-top: 10px;">
						<label for="description" >Front Description:</label> 
						
						
						<textarea  required  name="front_description" class="form-control" style="height: 60px;" maxlength="150" placeholder="" rows="5" id="front_description"></textarea>
						
					</div>



					<div class="form-floating"  style="padding-top: 10px;">
						{{-- <label for="file" style="margin-left: 20px;">Image (1620x2700):</label> --}}
						<input type="file" required style="padding-top: 20px;" class="form-control" id="front_file" name="front_file">
						{{-- {{ Form::file('file',null,['autofocus'=>'','required'=>'','class'=>'form-control','placeholder'=>'eg fastest cars in the world',  'maxlength'=>'1000', 'minlength'=>'1']) }} --}}
					</div>



				






					<div class="form-floating" style="padding-top: 10px;">
						<label for="feature" style="background: #fff;
							display: block;width: 96%;
							z-index: 20;
							height: 52px;
							margin-top: 11px;
							margin-left: 3px;">Facility(s):</label>
						<select name="facility[]"  id="facility" style="height: calc(10.5rem + 2px);padding-top: 40px;padding-top: 54px;" class="form-control" multiple="" aria-label="multiple select example">
							{{-- <label for="description" >Feature(s):</label> --}}
							{{-- 
							<optgroup selected="">Feature(s):</optgroup>
							--}}
							@if(count($facilities)>0)
							@foreach($facilities as $data)
							<option style="text-transform: capitalize;font-weight: bold;" value={{ $data->id }}>{{ $data->name }}</option>
							@endforeach
							@else
							<option style="" value="">No any facility registered.</option>
							@endif
						</select>
					</div>
					<div class="form-floating" style="padding-top: 10px;">
						<label for="description" >Description:</label> 
						
						
						<textarea   name="activity_desc" class="form-control" style="height: 100px;" maxlength="150" placeholder="Descriptions for this activity" rows="5" id="activity_desc"></textarea>
						
					</div>
					<div class="form-floating" style="padding-top: 10px;">
						<div class="form-check">
							<input class="form-check-input" type="checkbox" id="securityNotify" checked="" disabled="">
							<label class="form-check-label" for="securityNotify">
							Visible on website.
							</label>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>

resources/views/Inc/Modal/add_category.blade.php
<div class="modal fade" id="add_category" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add Category</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
       
            
            <form method="POST" action="{{  route('category.store') }}" enctype='multipart/form-data'>
				@csrf
				<div class="modal-body">
					<div class="form-floating" >
						<label style="margin-top: -11px;" for="name">Name:</label>
						<input type="text" class="form-control" placeholder="name" id="name" placeholder="Eg Jacuzzi" name="name">
						{{-- {{ Form::file('file',null,['autofocus'=>'','required'=>'','class'=>'form-control','placeholder'=>'eg fastest cars in the world',  'maxlength'=>'1000', 'minlength'=>'1']) }} --}}
					</div>


					

					<div class="form-floating" style="padding-top: 10px;">
						<label for="description" >Description:</label>
						<textarea   name="description" class="form-control" style="height: 100px;" maxlength="150" placeholder="Descriptions for this facility" rows="5" id="description"></textarea>
					</div>

                    
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>

      
      </div>
    </div>
  </div>

resources/views/Inc/Modal/add_exchange_rate.blade.php
<div class="modal fade" id="add_exchange_rate" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add Echange Rate</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
       
            
        <form method="POST" action="{{  route('exchange.store') }}" enctype='multipart/form-data'>
				@csrf
				<div class="modal-body">
					<div class="form-floating" >
						<label style="margin-top: -11px;" for="name">Price:</label>
						<input type="text" class="form-control" placeholder="name" id="name" placeholder="Eg Jacuzzi" name="name">
						{{-- {{ Form::file('file',null,['autofocus'=>'','required'=>'','class'=>'form-control','placeholder'=>'eg fastest cars in the world',  'maxlength'=>'1000', 'minlength'=>'1']) }} --}}
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>

      
      </div>
    </div>
  </div>

resources/views/Inc/Modal/add_facility.blade.php
<div class="modal fade" id="add_facility" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add Facility</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
       
            
            <form method="POST" action="{{  route('facility.store') }}" enctype='multipart/form-data'>
				@csrf
				<div class="modal-body">

					<div class="form-floating" >
						<label for="name" style="margin-top: -11px;">Name:</label>
						<input type="text" placeholder="name" class="form-control" id="name" placeholder="Eg Swimming pool" name="name">
						{{-- {{ Form::file('file',null,['autofocus'=>'','required'=>'','class'=>'form-control','placeholder'=>'eg fastest cars in the world',  'maxlength'=>'1000', 'minlength'=>'1']) }} --}}
					</div>
					

					
					<div class="form-floating" style="padding-top: 10px;">
						<label for="description" style="background: #fff;
						display: block;width: 95%;
						z-index: 20;
						height: 52px;
						margin-top: 11px;
						margin-left: 3px;">Feature(s):</label>
				
						

						<select name="feature[]"  id="feature" style="height: calc(10.5rem + 2px);padding-top: 40px;padding-top: 54px;" class="form-control" multiple="" aria-label="multiple select example">
							{{-- <label for="description" >Feature(s):</label> --}}
								{{-- <optgroup selected="">Feature(s):</optgroup> --}}
								@if(count($features)>0)
								@foreach($features as $data)
							<option style="text-transform: capitalize;font-weight: bold;" value={{ $data->id }}>{{ $data->name }}</option>
							@endforeach
							@endif
							

						  </select>



					</div>


					<div class="form-floating" style="padding-top: 10px;">
						<label for="description" >Description:</label>
						<textarea   name="description" class="form-control" style="height: 100px;" maxlength="150" placeholder="Descriptions for this facility" rows="5" id="description"></textarea>
					</div>
                    

					<div class="form-floating" style="padding-top: 10px;">
						{{-- <label for="file">Select picture (If Any):</label> --}}
						<input type="file" style="padding-top: 20px;"  class="form-control" id="file" name="file">
						{{-- {{ Form::file('file',null,['autofocus'=>'','required'=>'','class'=>'form-control','placeholder'=>'eg fastest cars in the world',  'maxlength'=>'1000', 'minlength'=>'1']) }} --}}
					</div>


					
					<div class="form-floating" style="padding-top: 10px;">
						
						<div class="form-check">
							<input class="form-check-input" type="checkbox" id="securityNotify" checked="" disabled="">
							<label class="form-check-label" for="securityNotify">
							  Visible on website.
							</label>
						  </div>
					</div>


					


				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>

      
      </div>
    </div>
  </div>

resources/views/Inc/Modal/add_feature.blade.php
<div class="modal fade" id="add_feature" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add Feature</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
       
            
            <form method="POST" action="{{  route('feature.store') }}" enctype='multipart/form-data'>
				@csrf
				<div class="modal-body">
					<div class="form-floating" >
						<label style="margin-top: -11px;" for="name">Name:</label>
						<input type="text" class="form-control" placeholder="name" id="name" placeholder="Eg Jacuzzi" name="name">
						{{-- {{ Form::file('file',null,['autofocus'=>'','required'=>'','class'=>'form-control','placeholder'=>'eg fastest cars in the world',  'maxlength'=>'1000', 'minlength'=>'1']) }} --}}
					</div>

                    
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>

      
      </div>
    </div>
  </div>

resources/views/Inc/Modal/add_gallery_category.blade.php
<div class="modal fade" id="create_gallery_category" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add Gallery Category</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
       
            
            <form method="POST" action="{{  route('gallery_category.store') }}">
				@csrf
				<div class="modal-body">
					<div class="form-group">
						<label>Name:</label>
						<input type="text" placeholder="Eg Surroundings" class="form-control input-default shadow-input" name="name" id="name" required >                   
					</div>
					<div class="form-group" style="padding-top: 10px;">
						<label>Description:</label>
						<textarea  name="description" class="form-control" maxlength="150" placeholder="Description about this category" rows="3" id="description"></textarea>
					</div>
                    
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
				</div>
			</form>

      
      </div>
    </div>
  </div>

resources/views/Inc/Modal/add_house.blade.php
<div class="modal fade" id="add_house" tabindex="-1" style="display: none;" aria-hidden="true">
	<div class="modal-dialog modal-dialog-scrollable ">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Add Room</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form method="POST"  action="{{  route('house.store') }}" enctype='multipart/form-data'>
					@csrf
					<div class="form-floating" >
						<label for="name" style="margin-top: -11px;">Name:</label>
						<input type="text" placeholder="name" class="form-control" id="name" placeholder="Eg Swimming pool" name="name">
					</div>
					<div style="display: inline-flex;">
						<div class="form-floating" style="padding-top: 10px;margin-right:10px;"  >
							<label for="floatingSelect1">Price Per Room:</label>
							<input type="number" required  class="form-control" id="cost"  name="cost">
						</div>
						<div class="form-floating" style="padding-top: 10px;margin-right:10px;">
							<label for="currency_id">Currency:</label>
							<select name="currency_id" id="currency_id" required class="form-select" required id="currency_id" aria-label="Floating label select example">
								@if(count($currencies)>0)
								<option selected="" value="">--Select Currency--</option>
								@foreach($currencies as $data)
								<option value={{  $data->id  }}>{{  $data->code }}</option>
								@endforeach
								@endif
							</select>
							
						</div>
						<div class="form-floating" style="padding-top: 10px;">
							<label for="currency_id" style="font-size: x-small;">Reference (Eg Per Month):</label>
							<input type="text" required placeholder="Eg Per Month"  class="form-control" id="Price_reference"  name="Price_reference">
						</div>
					</div>
					<div class="form-floating" style="padding-top: 10px;">
						<label for="number_of_rooms">Number Of Room:</label>
						<input required type="text"  class="form-control" id="number_of_rooms" name="number_of_rooms">
					</div>
					<div class="form-floating" style="padding-top: 10px;">
						<label for="max_number_of_children">Max Number Of Children Per Room:</label>
						<input required type="text"  class="form-control" id="max_number_of_children" name="max_number_of_children">
					</div>
					<div class="form-floating" style="padding-top: 10px;">
						<label for="max_number_of_adults">Max Number Of Adult Per Room:</label>
						<input required type="text"  class="form-control" id="max_number_of_adults" name="max_number_of_adults">
					</div>
					<div class="form-floating" style="padding-top: 10px;">
						<label for="name">Location:</label>
						<input required type="text" placeholder="name" class="form-control" id="location" value="{{  $organisation_location->name }}" name="location">
					</div>
					<div class="form-floating" style="padding-top: 10px;">
						<label for="name">Category:</label>
						<select name="category_id" id="category_id" required class="form-select" required id="floatingSelect2" aria-label="Floating label select example">
							@if(count($categories)>0)
							<option selected="" value="">--Select category--</option>
							@foreach($categories as $data)
							<option value={{  $data->id  }}>{{  $data->name }}</option>
							@endforeach
							@endif
						</select>
					</div>
					<div class="form-floating" style="padding-top: 10px;">
						<div class="form-floating" style="padding-top: 10px;">
							<input type="file" style="padding-top: 20px;border: dashed;border-color: #66A6BC;"  class="form-control" id="file" name="file">
						</div>
						<div class="form-floating" style="padding-top: 10px;">
							<label for="activity" style="background: #fff;
								display: block;width: 95%;
								z-index: 20;
								height: 52px;
								margin-top: 11px;
								margin-left: 3px;">Activities(s):</label>
							<select name="activity[]"  id="activity" style="height: calc(10.5rem + 2px);padding-top: 40px;padding-top: 54px;" class="form-control" multiple="" aria-label="multiple select example">
								@if(count($activities)>0)
								<option selected value="">--Select Activity--</option>
								@foreach($activities as $data)
								<option style="text-transform: capitalize;font-weight: bold;" value={{ $data->id }}>{{ $data->title }}</option>
								@endforeach
								@endif
							</select>
						</div>
						<div class="form-floating" style="padding-top: 10px;">
							<label for="facility" style="background: #fff;
								display: block;width: 95%;
								z-index: 20;
								height: 52px;
								margin-top: 11px;
								margin-left: 3px;">Facility(s):</label>
							<select name="facility[]"  id="facility" style="height: calc(10.5rem + 2px);padding-top: 40px;padding-top: 54px;" class="form-control" multiple="" aria-label="multiple select example">
								@if(count($facilities)>0)
								<option selected value="">--Select Facility--</option>
								@foreach($facilities as $data)
								<option style="text-transform: capitalize;font-weight: bold;" value={{ $data->id }}>{{ $data->name }}</option>
								@endforeach
								@endif							
							</select>
						</div>
						<div class="form-floating" style="padding-top: 10px;">
							<label for="description" >Description:</label>
							<textarea   name="description" class="form-control" style="height: 100px;" maxlength="150" placeholder="Descriptions for this facility" rows="5" id="description"></textarea>
						</div>
						<div class="form-floating" style="padding-top: 10px;">
							<label style="margin-top: -8px;
								margin-left: 10px;" for="isAvailable"  class="form-check-label" >Available:</label>
							<input class="form-check-input" checked="" type="checkbox" name="isAvailable" id="isAvailable">
						</div>
						<div class="form-floating" style="padding-top: 10px;">
							<div class="form-check">
								<input class="form-check-input" type="checkbox" id="securityNotify" checked="" disabled="">
								<label class="form-check-label" for="securityNotify">
								Visible on website.
								</label>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-primary">Save</button>
						</div>
				</form>
				</div>
			</div>
		</div>
	</div>
	
	

resources/views/Inc/Modal/add_image.blade.php
<div class="modal fade" id="add_image" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add Image</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
       
            
            <form method="POST" action="{{  route('image.store') }}" enctype='multipart/form-data'>
				@csrf
				<div class="modal-body">
					
					<div class="form-floating"  style="padding-top: 10px;display: contents;">
						{{-- <label for="file" style="margin-left: 20px;">Image:</label> --}}
						<input type="file" style="padding-top: 20px;" class="form-control" id="file" name="file">
						{{-- {{ Form::file('file',null,['autofocus'=>'','required'=>'','class'=>'form-control','placeholder'=>'eg fastest cars in the world',  'maxlength'=>'1000', 'minlength'=>'1']) }} --}}
					</div>


					<div class="form-floating" style="padding-top: 10px;">
						<label  for="category_id">Category:</label>
						<select class="form-select" name="category_id" id="category_id" aria-label="Default select example">

							@if(count($galleryCategory)>0)
							<option value="">Select category</option>

							@foreach($galleryCategory as $data)
							<option value={{ $data->id }}>{{  $data->name  }}</option>
							@endforeach
							@else
							<option value="" >Please add category</option>
							
							@endif
						  </select>
					</div>


					<div class="form-floating" style="padding-top: 10px;">
						<label for="quality_level">Resolution:</label>
						<select class="form-select" id="quality_level"  name="quality_level" aria-label="Default select example">
							<option selected="800" value="0">Default</option>
							<option  value="200">High</option>
							<option value="100">Medium</option>
							<option value="50">Low</option>
						  </select>
					 </div>



					<div class="form-floating" style="padding-top: 10px;">
						<label for="description">Description:</label>
						<textarea  name="description" class="form-control" style="height: 100px;" maxlength="150" placeholder="Description for this image" rows="3" id="description"></textarea>
					</div>


					<div class="form-floating" style="padding-top: 10px;">
						
						<div class="form-check">
							<input class="form-check-input" type="checkbox" id="securityNotify" checked="" disabled="">
							<label class="form-check-label" for="securityNotify">
							  Visible on website.
							</label>
						  </div>
					</div>
                    
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>

      
      </div>
    </div>
  </div>